### ISSUE TITLE
Speed up posh tests

### ISSUE THREAD

**Issue by FerdinandSpitzschnueffler** [eclipse-iceoryx/iceoryx#1030]
## Brief feature description

Some of our tests, e.g. when publisher subscriber communication is tested, call `InterOpWait` provided by the `RouDiEnvironment` to ensure that the discovery loop has been run through. Adding a function to the `RouDiEnvironment` to trigger the discovery loop manually would make these tests faster and more reliable.

In addition quite a lot of time is spent in `memset` to zero the shared memory. This time could be reduced by having a minimal mempool config for the tests. In addition, the introspection mempools should also be configurable via the `RoudiConfit_t`

## Tasks

- [x] add manual trigger for the RouDi discovery loop (e.g. via a `WaitSet` and a `UserTrigger`)
- [x] provide a `RouDiConfig_t` with a minimal memory footprint
- [x] add an option to `RouDiConfit_t` to configure the number of chunks for the introspection

**Comment by elBoberido** [comment]
@FerdinandSpitzschnueffler I discovered that there are more issues than the discovery loop and updated the issue accordingly.
