### ISSUE TITLE
Implement and test `nullptr` check in c binding

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1106]
## Brief feature description

Most of the C functions get as first argument a pointer to the class which they are handling. It  is possible that this pointer is a `nullptr` but this is in most functions not checked.

* Sometimes even payload pointer or pointer to other structs are provided which have to be also checked.
* `const char * ` arguments have to also be checked for `nullptr`

We have to implement and test such a check for all c binding functions.

## Detailed information

Example from `c_publisher.cpp`:
```c
void iox_pub_release_chunk(iox_pub_t const self, void* const userPayload)
{
    PublisherPortUser(self->m_portData).releaseChunk(ChunkHeader::fromUserPayload(userPayload));
}
```
`self` is the pointer to the publisher and can be a `nullptr`.

## ToDo:
- [x] ~~Implement #1113 first, then verify nullptr checks with an error handler that throws an exception.~~ `EXPECT_FATAL_FAILURE` can be used to test code which would lead to a termination in `Expects/Ensures` calls
- [ ] Check if ToDo list contains all affected constructs (if not add them)
- [ ] `c_chunk.cpp`
- [ ] `c_listener.cpp`
- [ ] `c_notification_info.cpp`
- [ ] `c_publisher.cpp`
- [ ] `c_subscriber.cpp`
- [ ] `c_user_trigger.cpp`
- [ ] `c_wait_set.cpp`
- [ ] Collect bonus points by coming up with a great idea/concept which prohibits such a oversight in the future.

**Comment by elfenpiff** [comment]
@elBoberido I would love it ...

**Comment by zmostafa** [comment]
It seems that all what is required here is to use this check `iox::cxx::Expects(self != nullptr);` @elBoberido mentioned here https://github.com/eclipse-iceoryx/iceoryx/pull/1303#discussion_r836570100 , or there is more to it ?

> Collect bonus points by coming up with a great idea/concept which prohibits such a oversight in the future

@elfenpiff What do you think of `not_null` pointer class and redefine all parameters with it as solution? I got the idea from this [article](https://www.cppstories.com/2017/10/notnull/) and I saw the class already under `iceoryx_hoofs`

**Comment by elfenpiff** [comment]
> It seems that all what is required here is to use this check `iox::cxx::Expects(self != nullptr);` @elBoberido mentioned here [#1303 (comment)](https://github.com/eclipse-iceoryx/iceoryx/pull/1303#discussion_r836570100) , or there is more to it ?
> 
> > Collect bonus points by coming up with a great idea/concept which prohibits such a oversight in the future
> 
> @elfenpiff What do you think of `not_null` pointer class and redefine all parameters with it as solution? I got the idea from this [article](https://www.cppstories.com/2017/10/notnull/) and I saw the class already under `iceoryx_hoofs`

Sounds great but when you are at it I would adjust the API from our `non_null` type. At the moment it has a constructor - please get rid of it completely! It should only be constructible via a factory method, see:
```
template<typename T>
class NotNull {
  public:
    // returns a nullopt when a nullptr is used as argument, otherwise it returns the NotNull inside the optional
    optional<NotNull> new(T* const ptr);
}
```

**Comment by elBoberido** [comment]
@elfenpiff @zmostafa we cannot use `not_null` in the C binding since C does not support templates ;)

Also, `new` cannot be used as method name. For that we have to switch to Rust ... don't tempt me ;)

**Comment by elfenpiff** [comment]
> @elfenpiff @zmostafa we cannot use `not_null` in the C binding since C does not support templates ;)
> 
> Also, `new` cannot be used as method name. For that we have to switch to Rust ... don't tempt me ;)

Hehe you are right, I should have read the context! I just thought we discuss the refactoring of the `not_null` type here.

**Comment by zmostafa** [comment]
@elfenpiff my bad, just trying to collect the extra points, and forgot about that C APIs bindings :sweat_smile: .

I know my luck, and the second I feel competent with C++ you will switch to Rust and will have to start the whole learning process again :rofl:

**Comment by zmostafa** [comment]
@elfenpiff I will pick this issue next for my todo, I just want to confirm on something.

I started with the function in the issue description as a PoC for the change

```cpp
void iox_pub_release_chunk(iox_pub_t const self, void* const userPayload)
{
    iox::cxx::Expects(self != nullptr);
    PublisherPortUser(self->m_portData).releaseChunk(ChunkHeader::fromUserPayload(userPayload));
}
```

and for the testing, I used first `EXPECT_FATAL_FAILURE` from gtest, but the unit test always ends when it reaches this error, no idea why, is it about the `substr` it should compare the return value against to evaluate the failure,as I do not know/write exact statement that returns from `Expects`.

I used the `IOX_EXPECT_FATAL_FAILURE` instead, and it seems working fine i.e. the test executes, passes , and the continues executing the rest unit tests
```cpp
auto hasFatalFailure = IOX_EXPECT_FATAL_FAILURE<iox::HoofsError>([&] { iox_pub_release_chunk(nullptr, chunk);},
                                                                     iox::HoofsError::EXPECTS_ENSURES_FAILED);
EXPECT_TRUE(hasFatalFailure);
```
What do you think ? I saw already `IOX_EXPECT_FATAL_FAILURE` is [the recommended way to do testing that is expected to fail](https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/design/error-handling.md#testing-fatal-error)

cc. @elBoberido

**Comment by elfenpiff** [comment]
@zmostafa I have to admit I never worked with `IOX_EXPECT_FATAL_FAILURE` before but when it works and it is described as best practice I would usually go for it.

The thing is that currently we are introducing a new error handling concept. It may also add new and incompatible ways to verify preconditions like `iox::cxx::Expects`.

So it maybe wise to postpone this task for a week until the PR #1902 is merged. The author @MatthiasKillat or the reviewers @elBoberido and @FerdinandSpitzschnueffler can provide you maybe further insights and tell you
* if it makes sense to start with your task right now
* how the API changes if it makes sense to wait for the moment
* or if we have some kind of transition from old to new API

**Comment by elBoberido** [comment]
@elfenpiff @zmostafa I think we do not need to wait. It might take some time until  that PR is merged and eventually it will provide a similar mechanism. Porting would not be that hard and time consuming.

You also do not have to check for the return value since there are already `EXPECT_*` in all paths and if there is no failure the tests fails.
