### ISSUE TITLE
Release validation for `v3.0`

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#1295]
## Website/Markdown settings

* [x]  ~~Add `.markdownlint.yaml` file~~ Moved to #2403 
* [x] Check Keys and [annotations](https://squidfunk.github.io/mkdocs-material-insiders/reference/code-blocks/#inlinehilite) features
* [x] ~~split images into a root folder with common images and one for the specific versions for the rendered SVGs~~ Moved to #2403 
* [x] update footer according to the new landing page
    * [x] copyright
    * [x] vertical social media links
    * [x] improved logos
* [x] adapt script for new landing page -> Only `index.html` was changed, which is not updated by the script `tools/website/export-docu-to-website.sh` 

## Common

* [x] Update architecture diagrams
* [x] Revise `doc/website/getting-started/installation.md`
* [x] Revise `tools/website/how-to-record-asciicast.md`
* [x] Write down questions that came up before in `FAQ.md`
* [x] Decision whether to remove the QAC Helix guide (Can this be maintained by Perforce?) `tools/HelixQAC/README.md`
* [x]  Add integration hints to other platforms
* [x]  Add separator for the API change sections
* [x]  ~~icedelivery: Explain lifetime semantics of chunks/samples and user restrictions: loan needs to be followed with publish or release, MAX_CHUNKS_IN_USE on publisher and subscriber side etc., API is not thread-safe, update asciinema record (@MatthiasKillat)~~ Moved to #2403 
* [x] Add Apex.AI logo in `.svg`

## Examples

* [x] ~~Rework `icediscovery` example~~ Moved to #2403 
* [x] ~~Fix broken example `SingleProcess` on Windows~~ Fixed in #1082

## Update

* [x] Update `installation-guide-for-contributors.md` article

## New articles

* [x] Add binding/extension article about Rust, ara::com and DDS Gateway
  * [x] Update `iceoryx_components_diagram_nextgen_release.puml` e.g. removing DDS Gateway
* [x]  ~~How to write integration tests~~  Moved to #2403
* [x]  ~~Performance results section~~ Moved to #2403
* [x] Add an article which describes den command line parameters of RouDi
* [ ] Add new article describing the long-term goals of `iceoryx2` and the transition strategy from the user perspective

## Release note

* [x] Add entry about `clang-tidy` and `AUTOSAR` warning fixes
* [x] Cherry-pick `v2.x.y` release notes to main branch

## Last tasks

* [x] ~~Re-record all changed asciinema recordings~~ Not necessary for only non-functional RouDi changes
    * #971 ~~changed the output of all `iox-roudi` recordings, maybe record roudi startup only once to avoid to record all examples when the roudi output changes.~~

**Comment by elBoberido** [comment]
Thanks creating this issue. Regarding the new articles. I think the last release showed that there most probably is no time for new articles so close to the release. Maybe we can concentrate earlier on this articles and then just need to proof read them during release validation. Maybe we should take some time in a developer meetup to talk about our release procedure and when we want to enforce which freezes, e.g. soft feature freeze, feature freeze, documentation freeze, dependency freeze, etc.

**Comment by mossmaurice** [comment]
@elBoberido

Everything seems up-to-date and sensible to address as part of the `v3.0` C-release besides:

> How to write integration tests
> Performance results section
> Add an article which describes den command line parameters of RouDi

I think for the sake of time we can skip those new articles and address them with `v4.0`.

My proposal regarding `iceoryx2` is to add a hint on the landing page and describe the long-term goals and transition strategy (that's what's most relevant to the user in a separate article under "Advanced").

**Comment by elBoberido** [comment]
@mossmaurice yes, sounds good.

The articles are also one of the reasons I would like to decouple the website from the tags. This gives us more freedom and we can just tag the articles for which version they are relevant.

**Comment by mossmaurice** [comment]
@elBoberido 

> [ ]  Add new article describing the long-term goals of iceoryx2 and the transition strategy from the user perspective

Do you think this is necessary to add to the iceoryx classic documentation? My feeling is this belongs more to the iceoryx2 docs which then also comes with some examples and maybe clang-tidy rules to refactor C++ code to move from iceoryx classic to the iceoryx2 C++ binding. Short-term this could also be added to the [index.html](https://github.com/eclipse-iceoryx/iceoryx-web/blob/main/index.html).
