### ISSUE TITLE
Add helper functions to `cxx::filesystem`

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1430]
## Brief feature description

In unit tests we sometimes require platform independent helper functions to modify directories. We should add functions like:
### Required
* `create_directory`
* `temp_directory_path` (used for file lock and sockets)
* `remove` & `remove_all`

### Optionally also:
* `exists`
* `is_directory`
* `is_regular_file`
* `is_socket`

It is important that those functions are working platform independently!

## ToDo

- [ ] Implement required features
- [ ] Implement optional features
- [ ] When this is implemented tests to the `FileLock` have to be added, see: https://github.com/eclipse-iceoryx/iceoryx/pull/1418#discussion_r907667097
