### ISSUE TITLE
Remove hash from the branch names

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#1530]
## Required information

**Operating system:**
all

**Compiler version:**
all

**Observed result or behaviour:**
Trying to use a branch with a hash in the name does not work with cmake FetchContent.

**Expected result or behaviour:**
Easy way to test iceoryx working branches with a FetchContent workflow.

**Conditions where it occurred / Performed steps:**
Try to use a branch with a hash, e.g. `iox-#42-foo` with the `iceoryx-project-template`

## Tasks

- [ ] adjust commit hooks for the new pattern for the branch name
    - both pattern shall be supported to ease the transition period
- [ ] adjust PR template
- [ ] adjust CONTRIBUTING.md

**Comment by elBoberido** [comment]
@mossmaurice there is not task in the checklist of the PR template in `iceoryx-project-template`
