### ISSUE TITLE
Automate check for test cases to have UUIDs

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#1540]
## Brief feature description

It's quite error prone to manually check if new test cases have unique UUIDs. The commit hooks and CI already check for unique UUIDs and the similarly it could be checked whether the count of `TEST`, `TYPED_TEST` and `TIMING_TEST` strings matches the count of `::testing::Test::RecordProperty` strings.

## Detailed information

It seems like the following simple grep commands can be used for a sanity check

```console
grep -rn --include="*.cpp" -e "^\(TEST\|TYPED_TEST\|TIMING_TEST\)" iceoryx_* | wc -l
grep -rn --include="*.cpp" TYPED_TEST_SUITE iceoryx_* | wc -l
grep -rn --include="*.cpp" "::testing::Test::RecordProperty" iceoryx_* | wc -l
```

The number of the first grep call minus the one from the second does match the number of the third one.

## Tasks

- [ ] add this check to the CI
- [ ] add this check to the git hooks
- [ ] remove the task to check for unique UUIDs from the PR template

**Comment by elBoberido** [comment]
@dkroenke @mossmaurice what do you think? This seems to work quite well and I could easily implement it. If it turn out to be  a bad idea we could still go back to the manual check.
