### ISSUE TITLE
Remove `EXPECT_DEATH`

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#1613]
## Required information

In our cases using `EXPECT_DEATH` come often with undefined behavior which is unacceptable for certified tests. Possible approaches are:

* Create thread and call `pthread_exit` inside the error handler, would require the implementation of that feature in #1365 
* Throw an exception in the error handler, would require heavy refactoring and feature #1392 
* Another nifty idea.

## ToDo
- [x] (high prio) Define an alternative technique to `EXPECT_DEATH` and document it in the iceoryx testing document
- [x] (high prio) Remove all occurrences of `EXPECT_DEATH` in cxx tests
- [x] (medium prio) Remove all occurrences of `EXPECT_DEATH` in remaining hoofs
- [ ] (low prio) Remove all occurrences of `EXPECT_DEATH` in the remaining iceoryx repo
  - Using `EXPECT_FATAL_FAILURE` in combination with the `RouDiEnvironment` results in triggering the leak sanitizer
  - The same is the case when the SUT allocate in the call which leads to the fatal failure, e.g. the ctor of `FileReader`

Can be split up in further issues when required.

Extracted from: #1196

**Comment by elBoberido** [comment]
@elfenpiff last week @MatthiasKillat tried the approach with returning from a running thread. This might be the solution to remove the `EXPECT_DEATH` once the error handler is merged.
