### ISSUE TITLE
Replace iox::byte_t with std::byte

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#1900]
## Brief feature description

Currently `iox::byte_t` is a `uint8_t`. Having a distinct type like C++17 [std::byte](https://en.cppreference.com/w/cpp/types/byte) helps to prevent issues with accidentally passing a `uint8_t` where a `iox::byte_t` is expected. 

## Detailed information

A drop in replacement for `std::byte` with C++14 is not possible since the compiler does not treat an `enum class byte : uint8_t {};` like an `unsigned char` and therefore the `strict aliasing` rule cannot be applied. With C++17 beside `char` and `unsigned char` also `std::byte` can be used. See also the `Type aliasing` section in [reinterpret_cast](https://en.cppreference.com/w/cpp/language/reinterpret_cast).

## Tasks

- [x] consolidate all `byte_t` types
- [x] rename `iox::byte_t` to `iox::byte`
- [x] use `std::byte` when switching to C++17

**Comment by elfenpiff** [comment]
@elBoberido this is a cool idea and I think we already have - maybe even multiple - definitions of that type.

Why an enum class and not a `NewType`?

**Comment by elBoberido** [comment]
@elfenpiff simple solution for simple problems ;)

The enum class is sufficient for this since we do not want to do any arithmetic with the type. We just want something which is 1 byte large and does not do anything.
