### ISSUE TITLE
Switch to C++17 on all platforms

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#2066]
## Brief feature description

C++23 was released earlier this year. We switched to C++14 around three years ago. Time to move to C++17.

## Detailed information

C++17 has some nice features like:
- structured bindings
  - e.g `auto [bar, baz] = foo();`
- new attributes
  - fallthrough, maybe_unused and nodiscard
- more constexpr
- initializers in `if` and `switch`
- class template argument deduction (CTAD)
- check if includes are available with `__has_include`

## Tasks

- [x] set the `ICEORYX_CXX_STANDARD` to 17 on all supported platforms
- [x] remove the `#if __cplusplus >= 201703L` switches
- [x] deprecate superfluous macros like `IOX_NO_DISCARD`
- [x] replace `iox::byte` with `std::byte`
- [x] ~~simplify the platform and remove duplicated headers by using `__has_include`~~ move to #2107
