### ISSUE TITLE
Add Cirrus CI

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#2070]
## Brief feature description

Cirrus CI offers native builds for FreeBSD an aarch64

## Detailed information

The FreeBSD CI is currently the most flaky one since it runs in a VM on macOS. Moving it to Cirrus CI should make it more reliable.

Additionally Cirrus CI also offers native aarch64 builds. This this should help us to identify bugs on this hardware platform.

Finally, running on Arch Linux should help us to find issues on non ubuntu systems.

## Tasks

- [x] move the FreeBSD build to Cirrus CI
- [x] add Ubuntu on aarch64 build to Cirrus CI
- [x] add macOS on aarch64 build to Cirrus CI
- [x] add Arch Linux to Cirrus CI
