### ISSUE TITLE
Additional functionality for `cxx::string`

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#208]
## Brief feature description

We require additional methods so that `cxx::string` is usable like `std::string`

## Detailed information
 * add method `cxx::string::clear` to clear the string
 
 * add method `cxx::string::operator[]()` to access a specific character of the string

 * assignment of `cxx::string` of different capacity
    ```
    iox::cxx::string<100> a;
    iox::cxx::string<29> b;
    a = b; // this should work

    iox::cxx::string<50> c(b); // this should work
    iox::cxx::string<50> c(a); // this should not work
    ```

  * `operator+=` and `operator+` for easy concatenation
    ```
    iox::cxx::string<100> a("hello");
    iox::cxx::string<100> b("world);

    a += b; // this should work
    iox::cxx::string<100> c = a + "world"; // this should work
    ```

  * `substr`
    ```
    iox::cxx::string<100> a("hello world");
    auto helloString = a.substr(0, 5); // should return iox::cxx::string<100> which contains "hello"
    auto worldString = a.substr(6); // should return iox::cxx::string<100> which contains "world"
    ```

  * `find`, `find_first_of`, `find_last_of` optionally

## Tasks

- [x] `find`, `find_first_of`, `find_last_of`
- [x] `operator+=`, `operator+`
- [x] assignment of `cxx::string` of different capacity
- [x] comparision operator between `cxx::string` and string literal or `char[]`
- [x] `operator[]`
- [x] `cxx::string::clear`
- [x] `insert`
- [ ] `append` + `concatenate` of simple chars
- [x] check if it's possible to have a `constexpr cxx::string`

## Refactoring tasks

- ~~[ ] check if it makes sense to define `using Self = string<Capacity>` in the header and use it within methods~~ - only two occurrences
- ~~[ ] in tests: replace `/// @note` with `// BEGIN tests for method xyz` to enable code folding on some IDEs~~ - seems to work only for Eclipse IDE and KDevelop, therefore postponed

**Comment by elBoberido** [comment]
@FerdinandSpitzschnueffler, does the c'tor automatically infer the length of string literals or do we have to use `TruncateToCapacity`?
It would be nice to be able to write `cxx::string<10> minion("Larry");` instead of `cxx::string<10> minion(TruncateToCapacity, "Larry");`

**Comment by FerdinandSpitzschnueffler** [comment]
@elBoberido, you're already able to write something like `cxx::string<10> minion("Larry")` as long as the size of the string literal is lesser than or equal than the cxx::string capacity.

**Comment by elBoberido** [comment]
@FerdinandSpitzschnueffler, nice. Maybe I overlooked it in the documentation.

**Comment by FerdinandSpitzschnueffler** [comment]
Regarding `operator[]` and `at()`:
Contrary to the `std::string` I would add a boundary check also to `operator[]`. The question is what should happen in case of an out of bounds access? I see only two options, 1) we terminate or 2) similar to the `unsafe_assign` we return a bool which indicates whether the access was successful. Thinking of something like `someString[index] = 'x'`, option 2 would make this cumbersome. Therefore, I tend to option 1. @elBoberido @elfenpiff What do you think? Do you see another option?

**Comment by elBoberido** [comment]
@FerdinandSpitzschnueffler I think calling `Expects` is the right way to do here. The alternative would be to return a `cxx::optional<T&>` which could be accessed with `and_then`. This would be quite cumbersome but maybe an option for `at()`. So there are two options to chose from, a safe one and one which might terminate

**Comment by mossmaurice** [comment]
@FerdinandSpitzschnueffler I second @elBoberido, `Expects/Ensures` is a good choice as we will later (#607) allow to disable the checks. You can have a look at [this PR](https://github.com/eclipse-iceoryx/iceoryx/pull/750/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.inl&file-filters%5B%5D=.md#diff-19b3ce30804b322cb7fd58c26dcb9dc880c902ee21516af7efa29b3d07a34287), where I adapted `cxx::vector` and `cxx::list` amongst other building blocks.

**Comment by mossmaurice** [comment]
@FerdinandSpitzschnueffler @elfenpiff 

Regarding:

> check if it's possible to have a `constexpr cxx::string`

I had a look yesterday: For #1332 I wanted to replace a

```
constexpr char MYLOVELYSTRING[] = "Blubb";
```

with

```
constexpr cxx::string MYLOVELYSTRING("Blubb");
```

turns out with owning string implementations (e.g. `std::memcpy`) it is only possible from C++20 and onwards, but even GCC and clang do [**not** support the feature for `std::string` in their current stable versions yet](https://en.cppreference.com/w/cpp/compiler_support). You can find the background in this [StackOverflow post](https://stackoverflow.com/a/70571714/18276160).

To avoid the usage of plain char arrays we could create a non-owning `cxx::string_view` and wrap them to have a nicer API, which will work in C++14. However, I don't see a huge benefit as we could then just wrap the char array in a `cxx::string` during runtime. What do you think?

**Comment by MatthiasKillat** [comment]
@mossmaurice I do not understand. The point of a view (e.g. `string_view`) not to own anything, but only reference the original and return a potentially transformed version to the user of the view, say only a substring or a reversed string etc.

Hence we still have to solve he problem that whatever the view references must exist and in your particular case also be constexpr. It is likely possible to have a view to a statically defined string constant (`const char * c = "abc";`). The view then needs to have constexpr constructor with this, which should work. 

However, to be generic/useful enough the view also should be able to deal with `cxx::string`, and this is more involved due to the capacity template argument. The complexity of the task depends on what kind of operations the view needs to support. IMO as a first prototype read access with `operator[]` and creation of a copy of the referenced string (as a `cxx::string`) would be useful and easy to achieve. Supporting the full array of string operations requires a lot of work and is probably not worth it for now.

If there is interest in creating such a view we can discuss this in detail in a separate issue.

@FerdinandSpitzschnueffler

**Comment by mossmaurice** [comment]
@csitarichie This is the issue I mentioned yesterday. Check out [my comment](https://github.com/eclipse-iceoryx/iceoryx/issues/208#issuecomment-1114045466) above on a `constexpr`'able `cxx::string`. You can find the implementation [here](https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp). If you see a possibility to implement it with C++14, I love to hear your idea :upside_down_face:
