### ISSUE TITLE
32-Bit Support

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#2301]
## Brief feature description

The main reason iceoryx is not running on 32-Bit CPUs are the lock-free algorithms. Our implementations rely on 8 byte (64 bit) CAS operations being lock-free. However, currently available 32bit CPUs often support 8 byte CAS.

### godbolt example with 64 bit data type

- [x86-64](https://godbolt.org/z/hd6TssebW)
- [x86-64 with '-m32' flag](https://godbolt.org/z/E1z3xcxM8)
- [arm64 with '-mtune=cortex-a53' flag](https://godbolt.org/z/xfedfzWTK)
- [arm64 with '-mtune=cortex-a53 -mabi=lp64' flags](https://godbolt.org/z/qs8cKnxh9)
- [arm64 with '-mtune=cortex-a53 -mabi=ilp32' flags](https://godbolt.org/z/cKPaPPGhj)
- [arm with '-mtune=cortex-a53' flag](https://godbolt.org/z/Kr8nMa4cv)

### Additional hurdles

- The `UsedChunkList` stores its data as 64 bit values and uses an atomic flag for synchronization for RouDi in case an application dies. With 32 bit CPUs this can lead to torn writes. These torn writes need to be detected when RouDi cleans up the remainder of a dead process.
- There are a ton on warnings, e.g. `usize_t` is smaller than `uint64_t` on 32 bit

## Tasks

- [ ] Use the C++17 `std::atomic<T>::is_always_lock_free` in all lock-free algorithms with a `static_assert` to prevent compilation on targets which do not support the atomic data type without a process local lock
- [ ] Adjust the `UsedChunkList`
- [ ] Fix all warnings on 32 Bit

## Related issues

- #562

**Comment by humanosc** [comment]
I'm experimenting with the v2.95.4 on a Linux debian arm 32 Bit (armv7l) based embedded system (with disabled ACL). 
I was wable to run the examples but I'm curious if there are any restrictions or known issues regarding 32 Bit support.
Are there any known limitations or issues (e.g. which may are related to the warnings: `conversion from 'long long unsigned int' to 'unsigned int' may change value [-Wconversion]`)?

**Comment by elBoberido** [comment]
@humanosc except those warnings, the only limitation compared to 64 bit support is a potential corruption of the so called `UsedChunkList`. If the application terminates right when it is writing into this structure, then the structure might be corrupted in a way that it will affect `RouDi` when it cleans up the resources.

Would iceoryx2 be an option for you? We are currently preparing the 0.6 release which will reach feature parity with iceoryx classic. So if you are not locked in to iceoryx classic, we would strongly recommend to switch to iceoryx2.

**Comment by humanosc** [comment]
@elBoberido iceoryx2 may an option but I'm unfimiliar regarding building the iceoryx2 rust code for the target platform (armv7l, debian bookworm). Currently I'm using GCC to cross compile.
