### ISSUE TITLE
New chunk available callback for the new C++ and C APIs 

### ISSUE THREAD

**Issue by budrus** [eclipse-iceoryx/iceoryx#350]
## Brief feature description

So far the new API allows for "normal" polling access and the usage in combination with a waitset. It shall also support the registration of callbacks similar to the old API

## Detailed information
The old API had the receive handler for this [see](https://github.com/eclipse/iceoryx/blob/master/iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp#L79). But instead of a thread per subscriber we should go for a thread in the runtime that handles the callbacks (could even be extended to a configurable thread pool in future) 

- [x] callbacks available for modern C++ API

- [x] callbacks available for C API

## ToDo

- [x] Write design proposal with an usage example
- [x] `enableEvent` in WaitSet attachable classes should have a signature so that they can be reused by the ReactAl. Change the signature to: 
```cpp
/// @return invalidation callback used by the WaitSet and ReactAl
cxx::MethodCallback<void, uint64_t> enableEvent(
                     const EventTypeEnum event, 
                     iox::popo::TriggerHandle & triggerHandle);
```

- [x] Implement design proposal
- [x] Rename `ActiveCallSet` into `Listener`
- ~~[ ] Create use case based comparison table between WaitSet and callback proposal~~ -> #482
- [x] Update example and write a user documentation
- [x] Add hint that the Listener does not take ownership of the callback. (In doxygen and user docu)
- [x] Rename EventInfo into NotificationInfo
- [x] Update design document to be in sync with the final implementation
- ~~[ ] Update Waitset and Listener section in [overview.md](https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/getting-started/overview.md)~~ -> #482 
- [x] Separate WaitSet State enums from Listener Event enums (`STATE_HAS_DATA`, `EVENT_DATA_RECEIVED`)
- [x] `hasTriggered`/`resetTrigger` refactoring in user trigger since it is automatically resetted

### Minor ToDo
- ~~[ ] `active_call_set.hpp` maybe merge indexmanager functionality into loffli~~ -> #680
- [x] Remove `doesContainEventVariable` from `TriggerHandle`.
- [x] Remove `setEventVariable` from `ChunkQueuePopper`.
- ~~[ ] Consider using the `index_queue` instead of `loffli` as `active_call_set` indexmanager~~ -> #680
- [x] do not iterate over array in `addEvent` ask event origin instead if event is already attached

**Comment by budrus** [comment]
To start the discussion, here the possible approaches I currently see. The problem we have to solve has similarities to the [event queue discussion in ROS 2](https://discourse.ros.org/t/ros2-middleware-change-proposal/15863). For me we also have to think about whether we use our waitset for managing the execution of callbacks or if we have an event queue as source of information. 

## Waitset Approach
- we already have it can can reuse it in our runtime (eat your own dog food)
- a thread in the runtime calls wait in a loop, when it returns the callbacks for all subscribers in the returned condition container are executed
-  we do not need to adapt the subscriber port, chunk receiver and chunk queue as we use the existing functionality with attaching a condition variable
- the chunks are collected in the chunk queue as usual (according to the capacity)
- we can use the guard condition to release the waitset (e.g. catching Ctrl-C end triggering the guard condition)
- I guess the waitset needs a mutex as we want to attach and detach callbacks during while the runtime thread is executing the `wait()` call see also #341
- Maybe the function_ref for the callback can be stored within the subscriber. Then the runtime does not have to do a bookkeeping for them, it only has to attach and detach subscribers to the waitset. How would we trigger the waitset call, via a public method of the subscriber is maybe a bad idea? 
- How do we ensure that we do not access a deleted subscriber or deleted callable?



### void, void callbacks
- we somehow need the contract that sample(s) are consumed in the callback. Otherwise the waitset will still indicate that there are available chunks and call the callback over and over again. 
- in the callback several samples could be taken and if all available are taken there will also be no further callback as the condition in the waiset is no more fulfilled 
- There is only one way to consume chunks amd this is the `take()` call on user API level 

### callback with chunk header

**Comment by budrus** [comment]
Ready for voting? @elfenpiff @FerdinandSpitzschnueffler @MatthiasKillat @dkroenke @elBoberido @ithier @marthtz @mossmaurice

**Comment by mossmaurice** [comment]
### Voting for B)

**Main reasons:**
* Eat your own dogfood, I think using our own `WaitSet`make sense and we quickly spot performance bottlenecks
* It's reusing our current classes (LEGO block approach) and does not introduce new patterns or classes (consistent with what we've done with the building blocks)
* I agree with you, that in case of going for B) we need a special e.g. `callbackTake()` for the `runtime`
* If we would go for a queue based approach: How would we statically dimension the queue? What would happen in the overflow case?

**Comment by elfenpiff** [comment]
@elBoberido your PR comment for later digestion

I constantly have to rethink the `hasTriggeredCallback` because I always think it's a boolean which tells that a callback has triggered and not a callback to check if the event has triggered.
What do you think about `triggerQueryCallback` (or maybe `queryCallback`)? This line would become
```
Trigger{&eventOrigin, triggerQueryCallback, invalidationCallback, eventId, eventCallback}
```
Doesn't need to be changed for this PR, just as food for thought.
