### ISSUE TITLE
Refine modern pub/sub API

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx#408]
_Originally posted by @budrus in https://github.com/eclipse/iceoryx/pull/360#discussion_r535725529_

How do we prevent this? With the old API people were more aware that they should not copy pointers that are coming from the middleware. In ara::com it's a unique ptr to make this even harder. I guess our Sample is also just an advanced unique_ptr but when I look at this code I fear that people think they must call `sample.get()` to be able to work with the payload. But in fact `get()` is the most dangerous method. 

We need `get` for frameworks where you get a Sample from the iceoryx API and have to pass e.g. a void* to the next layer (like in ROS). Then this layer has to return the pointer and the sample must be released with the iceoryx API. 
How would this look like? @elBoberido @ithier 

- take a sample
- get the raw pointer with `sample.get()`
- release the sample for not releasing the chunk when it goes out of scope, `sample.release()`
- pass the raw pointer to the next layer
- something happens
- raw pointer is returned from the next layer
- create a Sample with the raw pointer
- let the Sample go out of scope for releasing the chunk  

Shoud we make an example for this? This is a use case a lot people have. Would it be better to have a `release()` that releases the ownersip but additionally returns the pointer like in the STL and to remove the get() method? Having a get() that gives you a pointer to a shared memory chunk which is released when the Sample goes out of scope is a dangerous thing . The STL unique_ptr also has it but maybe people are more aware there 

Here in iceperf we want to copy the payload. How can we do something like `auto receivedSample = *(static_cast<const PerfTopic*>(receivedChunk));`?

With the `Sample` class, the `get` method and the fact that the subscriber has no `releaseChunk` method any more, the lifetime and ownership question has some complexity. This must be well documented in the new API docu @elfenpiff @FerdinandSpitzschnueffler @MatthiasKillat

**To-do:**
- [ ] Add offerAndSubscribeOnCreate to `PublisherOptions` and enable it as default (will close #575)
- [x] Remove `Sample` from untyped API and make it feel similar to the C-API (releaseChunk called by user)
- [x] Simplify the typed API, but not returning an `expected` but instead an `optional` and do the error handling for the user under the hood (fail fast & hard)
- [x] ~~Rename CaPro strings and add terminology table in overview.md~~
- [x]   Create a follow up issue that covers open points 
   - ~~define a payload_t or use void*?~~
   - using the header with the C API -> follow-up #585 
   - [x ]add a releaseChunk to the untyped publisher?

**Comment by elBoberido** [comment]
_Original response by @elBoberido in https://github.com/eclipse/iceoryx/pull/360#discussion_r536005352_

This is a tough question and boils down to the raw pointer access like you pointed out. I'm not sure how to fix this, except making it harder to get to a non-owning raw pointer. e.g. by replacing `get` with `dangerousNonOwningRawPointer` and hope the user is too lazy to type that much, doesn't have auto-completion and is scared enough to try other things first.

The `std::unique_ptr` return a pointer with the `release` call, so this would be the solution when an owning pointer is necessary. For the non-owning use case this would open the door to chunk leaks, which we want to prevent in the first place. At first we need to know what the user wants to do with the raw pointer. If it's just storing for later use, then we have to prevent this and encourage to store the sample. If it's for copying, we should maybe enrich the `Sample` API, e.g.
```
T getPayloadCopy();
copyPayload(void* buffer, uint64_t bufferSize);
```
With this, we could get rid of the `get` method

**Comment by elBoberido** [comment]
_Original response by @elfenpiff in https://github.com/eclipse/iceoryx/pull/360#discussion_r536119674_

I would clearly state in the docu: Please use the typed API but if you are an expert, you know what you are doing and you want to get your hands dirty then use the untyped one. With this statement and the assumption that the users know what they are doing we could get rid of the `Sample` and offer an interface which looks like this:
```cpp
untypedSubscriber->take().and_then([&](const void * payload){
     auto header = freeFunctionToAcquireHeaderPtr(payload);
     doStuff(payload, header);
  
     untypedSubscriber->releaseRawSample(payload);
});
```

You could also pack this `payload` and `header` pointer into a `Sample` but then the user is maybe mislead to believe that the sample takes care of the release but when having a `void*` you clearly have to take care of this.

Maybe it is also then useful to not recommend the functional approach and stick to the classic approach and use it like:
```cpp
auto payload = untypedSubscriber->take();
if ( !payload.has_value() ) {
    doStuff(payload.value()); // acquires void *
    untypedSubscriber->releaseRawSample(*payload);
}
```

**Comment by elBoberido** [comment]
_From a different PR posted by @elBoberido in https://github.com/eclipse/iceoryx/pull/403#discussion_r535183745_

@ithier what do you think about adjusting the `Sample::get` method to this
```
template <typename T>
class Sample {
public:
    template <typename U = T>
    U* get();

private:
    cxx::unique_ptr<T> m_samplePtr{[](T* const) {}};
};

template <typename T>
template <typename U>
U* Sample<T>::get() {
    static_assert(std::is_same<U, T>::value, "incompatible types");
    return m_samplePtr.get();
}

template <>
template <typename U>
U* Sample<void>::get() {
    return static_cast<U*>(m_samplePtr.get(););
}
```
then we could have
```
Sample<void> s;
auto untypedPointer = s.get();
auto typedPointer = s.get<Foo>();
```

**Comment by budrus** [comment]
Thanks @elBoberido for creating this follow up issue

**Comment by dkroenke** [comment]
Prasanna have a PR with the adress sanitizer enabled and it's throwing an interesting error when using the publisher     
Here the testcode:
```
     auto result = sut.publishResultOf([](DummyData* allocation) {
     auto data = new (allocation) DummyData();
     data->val = 777;
```

This is giving the following error:
`==51920==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60b0000676c7 at pc 0x0000004eae00 bp 0x7fff5b8d44e0 sp 0x7fff5b8d3c90
WRITE of size 8 at 0x60b0000676c7 thread T0`

According to the code the `publishResultOf` is calling `loan` which is creating the sample with plamenent new.
```
inline cxx::expected<AllocationError> TypedPublisher<T, base_publisher_t>::publishResultOf(Callable c,
                                                                                           ArgTypes... args)
{
    static_assert(....)

    return loan().and_then([&](Sample<T>& sample) {
        c(sample.get(), std::forward<ArgTypes>(args)...);
        sample.publish();
    });
}
```
```
inline cxx::expected<Sample<T>, AllocationError> TypedPublisher<T, base_publisher_t>::loan() noexcept
{
    // Call default constructor here to ensure the type is immediately ready to use by the caller.
    // There is a risk that the type will be re-constructed by the user (e.g. by using a placement new in
    // publishResultOf(), however the overhead is considered to be insignificant and worth the additional safety.
    return std::move(base_publisher_t::loan(sizeof(T)).and_then([](Sample<T>& sample) { new (sample.get()) T(); }));
}
```
So we have two places now with placement new and it seems that the one in `loan` is somehow then overoverwriting the one from the lambda expression. The comment in loan is somehow already assuming it.

**Comment by elBoberido** [comment]
> So we have two places now with placement new and it seems that the one in `loan` is somehow then overoverwriting the one from the lambda expression. The comment in loan is somehow already assuming it.

How about discouraging the usage of placement new in user code. We could just have a `Sample::emplace()` method which takes care of this. So if the sample already manages an object, it can call the destructor of the object.

Similarly 
```
     auto result = sut.publishResultOf([](DummyData* allocation) {
     auto data = new (allocation) DummyData();
     data->val = 777;
```
would become
```
     auto result = sut.publishResultOf([](Sample<DummyData> sample) {
     sample.emplace(DummyData);
     sample->val = 777;
```

**Comment by budrus** [comment]
posted by @MatthiasKillat in [#421 comment](https://github.com/eclipse/iceoryx/pull/421#discussion_r542441166)



Actually, it is not quite as easy with type inference in play like this due to overloads of and_then I think... I will look at the reason, but the call *sample.get() will not work anymore with auto since it is now detected to be an optional of sample, which is not what it should be (incorrect monadic behavior in my book). Now, changing the call to account for this seems to not play nicely with auto and it breaks.

Will need a closer look.
Message: the nested optionals samples and optionals and different overloads for and_then (some incorrect I think) are not working nicely to create an easy user experience.

**Comment by budrus** [comment]
capability to configure history is missing in new cpp publishers and subscribers

**Comment by MatthiasKillat** [comment]
@elBoberido I agree, emplacement new on the user side is a bad idea. Especially if there is already something constructed at this memory location (which would need to have a destructor called manually).
If we allow this, it should only be via void* I think (not a typed pointer) and if there is already something constructed there we should pass a reference instead.

My reasoning is that as a user I have a harder time to know whether the pointer points to just memory (even if typed) or to an already constructed object. With references I assume it is a valid sample. You can always circumvent this and mislead the user and have dangling references and, but this is bad style.

But we need something with at least the void pointer for interaction with low level APIs.

Accessing the data via the ``Sample::get`` method is also not ideal, since a raw pointer is exposed. I was also playing around with the idea of adding ``T& Sample::operator*``, but this is also not straightforward since T can be void, so (quite) a bit template magic is needed (i used SFINAE, there may be an easier way except fully specializing for void) and it just gives a another way to access the data with the same problem.

Anyway, a true monadic and_the must work with unpacked base type, but what is the unpacked type here? Consider the following: 
```auto result =  subscriber.take();```
Result is now something like a monad (not quite but good enough for us here), it most likely should not just be an expected, which is not specialized enough for the use case I think. Whatever payload type T it augments, I want to get a reference in the function I call in the in the and then.
```auto f = [](T& data) { ,,, };```
It is not useful to have an optional here, we should be able to guarantee that when we are in the and_then case, that we actually have data. Now it is also clear that f works on a reference, it may of course copy it internally, but it neither does own it nor is it responsible for its destruction.

Everything else belongs to different cases.
Now I can call 
```result.with_data(f).if_empty(g).or_else(h);```
with suitable g and h, with or_else being the catch all for the remaining cases when there is an error but.

**Comment by budrus** [comment]
The untyped C++ API needs some modifications

- It is not possible to take the ownership for the chunk. The `Sample` has no `release`. But we need this e.g. if a void* has to be passed to a higher layer and we do not want to store the Sample somewhere to prevent it from releasing the chunk (see also [take of loaned message in rmw_iceoryx](https://github.com/ros2/rmw_iceoryx/blob/master/rmw_iceoryx_cpp/src/rmw_take.cpp#L246))

- When a void* of a processed chunk is received from a higher layer, we would need to create a Sample for being able to release the chunk. There is no other way currently. This would also only be possible when introducing the `release` (see also [return of loaned messages in rmw_iceoryx](https://github.com/ros2/rmw_iceoryx/blob/master/rmw_iceoryx_cpp/src/rmw_take.cpp#L293)

The lifetime of the chunk on subscriber side is currently coupled to the `Sample` object. For a use case like rmw_iceoryx where we have to pass and receive void* to/from the next higher layer in separate methods, the consequence would be to introduce a storage of `Samples` or to work with `release`. When working with `release` we would have to create temporary Samples for releasing chunks, which feels a bit clumsy

I would make the untyped C++ API more similar to the C API. I.e. getting and releasing void* chunks. We made the wrong pair similar to each other. Untyped C++ and C (which is untyped too) are the real buddies.

**Comment by budrus** [comment]
I would make the typed C++ API even simpler

- For people who want to use iceoryx directly the typed API is normally the way to go
- The typed C++ is the first API we introduce in our docu and it should be as KISS as possible for having an easy start into iceoryx
- These people are often no interested in taking care of everything that can go wrong. Having an atomatic fail fast and clear strategy would be the best fit for most of them (e.g. "Hey, you are holding too many samples, you must reconfigure or you are doing something wrong", or "Hey, you are running out of chunks, you should check if your mempool config really fits to your needs"). 

When we do the error handling in the typed C++ API Code, `loan()` always returns a sample or terminates the application. We could also think of printing a warning and block until there is a chunk available. Which would be a behavior many would expect. The take would not return that complicated expected of an optional but only an optional.

**Comment by budrus** [comment]
In 90% of the use cases `offer()` is called directly after creating a publisher and `subscribe()` is called directly after creating a subscriber. For ara::com we have to start with a not offered publisher and a not subscribed subscriber. But it would be good to have a default offer-on-create for a publisher and subscribe-on-create for a subscriber. This could be controlled by our new introduced options for publishers and subscribers. 

A big benefit would be that we can potentially do the connection of publishers and subscribers when creating them. This would lead to a faster connection as we do not have to wait for the discovery loop. 

We also discussed this topic in #413

**Comment by elfenpiff** [comment]
Some more minor things:
- `iox::popo::Sample` should have `operator bool() const` implemented and return true if it holds a pointer, otherwise false (similar to `std::unique_ptr`).
- `iox::popo::Sample` should have a dereferencing operator `T& operator*()` (similar to `std::unique_ptr`).
- `publisher.take().and_then([&](auto & sample){})` type deduction leads to `cxx::optional<iox::popo::Sample<SomeType>>&` but it should be either `iox::popo::Sample<SomeType>` or even better, just `SomeType&`

**Comment by budrus** [comment]
Result of discussions 2021/01/11 with @MatthiasKillat @elBoberido @elfenpiff @mossmaurice  

TODO for iceoryx_1.0

** Untyped C++ API:
- Look & feel more like the C API and not like the typed C++ API
- Untyped API shall not use the `Sample` abstraction, we are working with chunks 
- Untyped `takeChunk()` returns expected. When there is no chunk returned expected can have "NO_CHUNK_AVAILABLE" , "TOO_MANY_CHUNKS_HELD_IN_PARALLEL". On success return a void* to the payload. ChunkHeader can be obtained from payload pointer via ChunkHeader::fromPayload(). The type shall be called *Result and not *Error
- Untyped needs then a `releaseChunk() `method which takes a void* to the payload
- No more Sample on publisher side, introduction of  loanChunk, freeChunk, publishChunk
- Does the untyped API then still use the base classes, or will the typed use the untyped? 

** Typed C++ API
- take() is changed to return only an expected. Like for the untyped the result type contains NO_CHUNK_AVAILABLE" , "TOO_MANY_CHUNKS_HELD_IN_PARALLEL". If a `Sample` is returned this is always a valid sample
- Besides` loan()` there shall be a `loanUnitialized()`. The Sample class shall be extended with an `emplace()` method 
- `Sample` class shall be extended with Operator* and operator bool
- remove `if_empty()` from expected again
- Remove "Typed" in the name of publisher and subscriber classes 

** C API:
- Rename NO_CHUNK_RECEIVED in C API to NO_CHUNK_AVAILABLE, Rename `get_chunk `of C API to `take_chunk`
- Wrapper method for getting the ChunkHeader from the payload pointer
- Rename allocate_chunk in loan_chunk
- Rename send_chunk  in publish_chunk
- Rename try_get_previous in loan_previous
- Introduction of option structs 
- Remove "try" in method names

** Options
- OfferOnCreate and SubscribeOnCreate shall be introduced

**Comment by MatthiasKillat** [comment]
We can consider adding the possibility of getting the ChunkHeader or other metadata from the Sample via an appropriate function of the typed API. This is available in the C-API as well and might also be useful when we implement more QoS or just generally add more info to samples.

It is not necessary for 1.0 though.

**Comment by budrus** [comment]
@MatthiasKillat the `Sample` class already has a [getHeader method](https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_posh/include/iceoryx_posh/popo/sample.hpp#L61)

**Comment by FerdinandSpitzschnueffler** [comment]
Please see also [#532](https://github.com/eclipse-iceoryx/iceoryx/pull/532/files#r567795431) for the introduction of the options struct in the C API.

**Comment by MatthiasKillat** [comment]
Open for discussion 
1. add a function to iox::popo to convert payload ptr to header (currently done by ``iox::mepoo::ChunkHeader::fromPayload``)
2. SampleDeleter holds a reference to the port now, hence relies on its lieftime, it would be better to have it rely on PortData or even the runtime. This requires some thoughts and refactoring (PortData is inaccessible from a Port and it can be argued whether access should be public). Runtime would be the best option (lifetime is assumed by iceoryx apps) but requires most refactoring.
3. Decide on common behavior for freeChunk and releaseChunk used by different ports. Which do we want to keep, how should it behave?
