### ISSUE TITLE
Remove #define private public from all tests

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#529]
## Required information
In some of the iceoryx tests are defines used for making private=public which is against our principle of white-box testing.
Additionally this doesn't compile on windows.

## Task
- [ ] remove `#define private public` and `#define protected public` from all testfiles
    - [x] test_gw_gateway_discovery.cpp (part of ##501)
    - [x] test_roudi_service_registry.cpp (trivial)
    - [x] test_objectpool.cpp (easy by making protected accessor methods; the objectpool might be removed in the future though)
    - [x] test_mq_interface.cpp (intermediate; mq_interface will be refactored in the near future though)
    - [ ] test_posh_mepoo.cpp (non-trivial and probably difficult)

**Comment by elBoberido** [comment]
oh, I also added it to the Windows Issue.
Nevertheless, `test_gw_gateway_discovery.cpp` will be fixed with the Duration PR

**Comment by dkroenke** [comment]
@elBoberido yes right, this is for the new contributors to get familiar.

**Comment by elBoberido** [comment]
@dkroenke I had a look at it yesterday and at least one is not quite trivial to solve. Shall I tag the files from easy to difficult?

**Comment by dkroenke** [comment]
@elBoberido Yes that definitely make sense

**Comment by elBoberido** [comment]
@dkroenke done. I think mq_interface will be refactored in the near future and should maybe be done with that refactoring
