### ISSUE TITLE
Refactor Relocatable Pointer and Relative Pointer

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx#605]
## Brief feature description

The relocatable pointer (`iceoryx_utils/internal/relocatable_pointer`) implementation needs to be cleaned up:

 1. [x] add noexcept, const, replace `size_t` with `uint64_t` (done in #618 except making parameters const)
 2. [x] separate implementation and declaration for all classes (#618)
 3. [x] one class per header file (#618)
 4. [x] add subnamespace `iox::rp` where everything is stored (#618)
 5. [x] ~~restructure the unit tests / add missing tests~~ Moved to #1745
 6. [x] add doxygen documentation (#618)
 7. [x] remove includes of base_relative_ptr.hpp & base_relocatable_ptr.hpp
 9. [x] ~~consider removing ``ptr_t`` and ``const_ptr_t`` aliases and use ``void*`` directly (see https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597604809)~~
 10. [x] ~~add ``void* get() noexcept``, ``const void* get() const noexcept``, ``void* getBasePtr() noexcept`` and ``const void* getBasePtr() const noexcept`` to BaseRelativePointer~~ -> Not implemented as `SharedPointer` uses `get() const noexcept`
 11. [x] ~~consider changing return type of ``PointerRepository::unregisterPrt()`` to ``void`` (see https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597609248)~~ - Note: maybe not, it might be useful to have an indication whether the deregistration was successful
 12. [x] move duplicated code into a separate method (see https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597613171)
 13. [x] rename ``PointerRepository::registerPtr()`` methods if both are needed (see https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597613855) + consider returning a ``cxx::unique_ptr<id_t>``
 14. [x] check invalid id logic (see https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597617681 and https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597619467)
 15. [x] ~~add const methods to RelativePointer (see https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597620985, https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597621144 and https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597621263).~~ This might not be needed, compare with e.g. std::shared_pointer https://en.cppreference.com/w/cpp/memory/shared_ptr/operator* It should work similar to STL smart pointers.
 16. [x] invalidate ``other`` move c'tor and move assignment operator of BaseRelocatablePointer (see https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597626715 and https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r597628041)
 17. [x] use composition instead of inheritance (see https://github.com/eclipse-iceoryx/iceoryx/pull/618#discussion_r599596822 and https://github.com/eclipse-iceoryx/iceoryx/issues/605#issuecomment-806045008) - if done, consider renaming Base...Pointer to Untyped...Pointer
 18. [x] ~~replace `RelativePointer` by `RelocatablePointer` where applicable, e.g. `Semaphore` and `LoFFLi`~~ Moved to #1745
 19. [x] Move `RelativePointer` to public include

**Comment by elBoberido** [comment]
I just thought about the refactoring. Currently there are two classes, `BaseRelativPointer` and `RelativPointer`. The former one is untyped and the latter one typed with a template parameter. Neither of those is trivially copyable, which requires de-structuring (e.g. with the `ChunkTuple` in `ChunkQueuePusher`) when put into a queue for shm communication. Additionally, its 16 bytes and can therefore also not be written in on clock cycle, even if it would be trivially copyable.

I would suggest to make the static functions of `BaseRelativPointer` free functions, since there is now the `rp` namespace, e.g. `rp::registerRelativePointer`. With this change it should be easy to merge `BaseRelativPointer` and `RelativPointer` into a single class and just use `void` as template parameter if an untyped relative pointer is required.

Furthermore, to make the de-structuring superfluous another struct will be introduced `RelativePointerData` like proposed here https://github.com/eclipse-iceoryx/iceoryx/issues/623#issuecomment-803986280 and used to fix the torn write in the `UsedChunkList`
```c++
    struct RelativePointerData
    {
        constexpr RelativePointerData() noexcept
            : segment(MAX_SEGMENT)
            , offset(MAX_OFFSET)
        {
            static_assert(sizeof(RelativePointerData) <= 8U, "The RelativePointerData size must not exceed 64 bit!");
            static_assert(std::is_trivially_copyable<RelativePointerData>::value,
                          "The RelativePointerData must be trivially copyable!");
        }
        constexpr RelativePointerData(uint16_t segment, uint64_t offset) noexcept
            : segment(segment)
            , offset(offset & MAX_OFFSET)
        {
            cxx::Ensures(offset < MAX_OFFSET && "offset must not exceed MAX:OFFSET!");
        }

        uint16_t segment : 16;
        uint64_t offset : 48;

        void reset()
        {
            constexpr RelativePointerData NULLPTR_EQUIVALENT{};
            *this = NULLPTR_EQUIVALENT;
        }

        bool isNullptr()
        {
            return segment == MAX_SEGMENT && offset == MAX_OFFSET;
        }

        static constexpr uint64_t MAX_SEGMENT{std::numeric_limits<uint16_t>::max()};
        static constexpr uint64_t MAX_OFFSET{(1ULL << 48) - 1};
    };
```
This would be the member of `RelativPointer` and could also replace the `ChunkTuple`.

To keep the reviewer happy, this could be done in three steps
- static functions to free functions
- introduce `RelativePointerData` struct
- merge the two classes

What do you think?

**Comment by mossmaurice** [comment]
Moved open tasks to #1745
