### ISSUE TITLE
Improve documentation and website for v2.0

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx#743]
# Brief feature description

### Website/Markdown settings

* [x] Open Bugzilla issue to "enforce https"
* [x] Create favicon for website
* [x] Switch to `mike` v1.0 to avoid duplication for aliases
* [x] ~~Add `.markdownlint.yaml` file~~ Moved to #1295

### Common

* [x] Improve utils documentation (in the long run: find more suitable name for utils, e.g. safe building blocks), see also #468
* [x] Add overview graphic introducing the main players (RouDi, Runtime/user apps, shared Memory, data packages/topics) in overview.md (see suggestions [here](https://github.com/eclipse-iceoryx/iceoryx/pull/646#discussion_r604950011) and [here]
(https://github.com/eclipse-iceoryx/iceoryx/pull/646#discussion_r604960591))
  * [x] Include GIF on iceoryx.io
  * [x] Add flow diagram for WaitSet and Listner (draw.io?)
* [x] Add link to CONTRIBUTING.md?
* [x] ~~Add integration hints to other platforms~~ Moved to #1295 
* [x] Describe introspection client in more detail, maybe refer to ROS 2 use-case?
* [x] Validate all the iceoryx articles at https://iceoryx.io/ -> Related to https://github.com/eclipse-iceoryx/iceoryx/issues/743
* [x] Double check: are the iceoryx integration tests covering all the examples?
* [x] Is the changelog is complete?
* [x] ~~Add separator for the API change sections~~ Moved to #1295 

### New articles/examples

* [x] Add chunk header example
* [x] Add example sending complex data types
* [x] Add section on CI setup (e.g. Axivion)
* [x] Add pub/sub matching criteria table
* [x] Add architecture article under concepts
* [x] Replace all GitHub link with fixed version `https://github.com/eclipse-iceoryx/iceoryx/tree/v2.0.0/`
* [x] ~~How to write integration tests~~ Moved to #1295 
* [x] Record asciicast for
  * [x] icecrystal (outdated)
  * [x] icedelivery
  * [x] icediscovery
  * [x] icediscovery_in_c
  * [x] ~~icedocker~~
  * [x] ~~iceensemble (outdated)~~
  * [x] ~~iceperf~~
  * [x] maybe: request_response - the waitset/listener example is described, recorded the basic example
  * [x] request_response_in_c

### Obligatory fixes

* [x] Fix doxygen function links
* [x] Fix broken links
  * [x] icecrystal example (tools/introspection)
  * [x] 2nd `hasInvalidStateMember` https://iceoryx.io/v1.0.0/API-reference/utils/Files/expected_8inl/
  * [x] 2nd `has_signature` https://iceoryx.io/v1.0.0/API-reference/utils/Files/type__traits_8hpp/
* [x] vicedelivery: Explain lifetime semantics of chunks/samples and user restrictions: loan needs to be followed with publish or release, MAX_CHUNKS_IN_USE on publisher and subscriber side etc., API is not thread-safe, update asciinema record (@MatthiasKillat)~~ Moved to #1295 

### Review design docs (@elfenpiff )
* [x] top level readme
* [x] chunk header
* [x] error handling
* [x] listener
* [x] `doc/design/lockfree_queue.md` (@MatthiasKillat )
* [x] relocatable pointer (@MatthiasKillat )
* [x] request response communication
* [x] service discovery
* [x] template

### Ideas

* [x] ~~Blog post section?~~ Not relevant
* [x] ~~Performance results section?~~ Moved to #1295 
* [x] ~~Add conference / community section with chat, dev meetup, mailing list (or help and ressources?)~~ Not relevant
* [x] ~~Add Cyclone DDS link~~ Not relevant
* [x] ~~Mention Eclipse Foundation and OpenADx on start page, also Default middleware together with Cyclone DDS~~ Not relevant

### Strech goals

* [x] ~~Check Keys and [annotations](https://squidfunk.github.io/mkdocs-material-insiders/reference/code-blocks/#inlinehilite) features~~ Moved to #1295

**Comment by fred-apex-ai** [comment]
@mossmaurice 

I would be great to describe the introspection client. Without it, it's hard to know whether a connection in ROS 2 is made through cyclone or iceoryx. The tool itself is really useful.

While I"m at it: I couldn't scroll the client, so with 160 connections, I couldn't see all of them even though the terminal  was in fullscreen `mode. In the [asciinema recording](https://asciinema.org/a/407442), you scroll.  How did you do that?

**Comment by mossmaurice** [comment]
@fred-apex-ai 

> I would be great to describe the introspection client in a bit more details. Without it, it's hard to know whether a connection in ROS 2 is made through cyclone or iceoryx. The tool itself is really useful. I found the output a bit hard to understand because roudi gave the processes different names than the system, as shown by `htop`.

Ok, noted. I added a todo. Thanks for the feedback.

> While I"m at it: I couldn't scroll the client, so with 160 connections, I couldn't see all of them even though the terminal was in fullscreen `mode. In the [asciinema recording](https://asciinema.org/a/407442), you scroll. How did you do that?

I was using the up and down arrow keys.
