### ISSUE TITLE
Use `cxx::function` were it is appropriate

### ISSUE THREAD

**Issue by MatthiasKillat** [eclipse-iceoryx/iceoryx#831]
## Brief feature description

We have some `std::function` usages left in iceoryx hoofs. They should be replaced with `cxx::function`.
This affects constructs needing callbacks, like `GenericRAII` (a better name would be `RAIIGuard` or similar) and others.
Furthermore constructs that are not used like `ActiveObject` are also affected.

Note that there are no direct occurrences in posh (but indirectly, via hoofs).

## Detailed information

We can replace them with `cxx::function` but need to choose its capacity carefully, likely on a case by case basis. We may have something global like `cxx::function<Signature, 100>` as well, in memory of its deceased cousin `string<100> `.

It could make sense to have some default (not 100 though, we should use powers of 2).  Still a specific case can be used on a case by case basis also (we will learn what works best by trying it for some cases). For internal use, i.e. no user defined callbacks, this makes sense sinc ewe can just increase the capacity if needed later (it will not compile in this case).

User defined callbacks are a a different matter, but we need a bound here as well.

This issue may be broken down further to handle specific occurrences of `std::function` should it prove more complex.

## Tasks

* [x] Replace or remove `std::function` in `iceoryx_hoofs`
* [ ] Replace `MethodCallback` with `cxx::function`
* [ ] Remove `MethodCallback` from `iceoryx_hoofs`

**Comment by elBoberido** [comment]
@mossmaurice do you think the `MethodCallback` can also be replaced in the context of this issue?

**Comment by mossmaurice** [comment]
> @mossmaurice do you think the `MethodCallback` can also be replaced in the context of this issue?

That's a good idea. I would defintely do it in separate PRs. However, I think this will be quite some effort. But removing `MethodCallback` sooner than later would be great.

**Comment by elBoberido** [comment]
@mossmaurice shall I extend the issue name ("Use cxx::function were it is appropriate") and add two tasks, one for `std::function` and one for `MethodCallback`?

**Comment by elfenpiff** [comment]
@MatthiasKillat @mossmaurice @elBoberido 

I added a subtask to also remove the `MethodCallback`. This was only a quick solution to capture `this` in a callback and with `cxx::function` this abstraction is not needed anymore.
